language: node_js
node_js:
  - "node"

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

script:
  - npm run build:chrome
  - npm run build:firefox
  - npm run build:opera
  - npm run build:edge
