name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install and build all browsers
        run: |
          yarn
          yarn build:chrome
          yarn build:firefox
          yarn build:opera
        env:
          CI: true
